[[redirects]]
  from = "/api"
  to = "https://api-anshcompany.koyeb.app/api:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
