[[redirects]]
  from = "/proxy/*"
  to = "https://api-ansh9436.koyeb.app/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[redirects]]
  from = "/dothome/*"
  to = "http://ansh.dothome.co.kr/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
